"""
scripts/deploy_contract.py — Deploy TouristIdentity contract to local blockchain.

Usage:
    python scripts/deploy_contract.py

Prerequisites:
    1. Local blockchain node running (Hardhat/Ganache): docker compose up blockchain
    2. BLOCKCHAIN_PROVIDER_URL set in .env (default: http://localhost:8545)
    3. BLOCKCHAIN_PRIVATE_KEY set (use a Hardhat default test account key in dev)

After deployment, set BLOCKCHAIN_CONTRACT_ADDRESS in .env.
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

# Allow running from project root
sys.path.insert(0, str(Path(__file__).parent.parent))

from web3 import Web3
from web3.middleware import geth_poa_middleware

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
PROVIDER_URL = os.getenv("BLOCKCHAIN_PROVIDER_URL", "http://localhost:8545")
PRIVATE_KEY = os.getenv("BLOCKCHAIN_PRIVATE_KEY")
CHAIN_ID = int(os.getenv("BLOCKCHAIN_CHAIN_ID", "1337"))

# Contract source (compile via solc or use pre-compiled ABI/bytecode)
CONTRACT_SOL = Path(__file__).parent.parent / "contracts" / "TouristIdentity.sol"
# Pre-compiled JSON (generated by Hardhat compile)
COMPILED_JSON = Path(__file__).parent.parent / "contracts" / "TouristIdentity.json"


def compile_contract() -> tuple[str, str]:
    """
    Compile TouristIdentity.sol and return (abi, bytecode).
    Uses py-solc-x if available; otherwise reads pre-compiled JSON.
    """
    if COMPILED_JSON.exists():
        print(f"Using pre-compiled contract: {COMPILED_JSON}")
        with open(COMPILED_JSON) as f:
            compiled = json.load(f)
        abi = compiled.get("abi") or compiled.get("output", {}).get("abi", [])
        bytecode = compiled.get("bytecode") or compiled.get("output", {}).get("evm", {}).get("bytecode", {}).get("object", "")
        return json.dumps(abi), bytecode

    try:
        from solcx import compile_source, install_solc
        print("Compiling TouristIdentity.sol with py-solc-x...")
        install_solc("0.8.20")
        source = CONTRACT_SOL.read_text()
        compiled = compile_source(
            source,
            output_values=["abi", "bin"],
            solc_version="0.8.20",
        )
        contract_key = next(k for k in compiled if "TouristIdentity" in k)
        abi = json.dumps(compiled[contract_key]["abi"])
        bytecode = compiled[contract_key]["bin"]
        return abi, bytecode
    except ImportError:
        raise RuntimeError(
            "py-solc-x not installed and no pre-compiled JSON found.\n"
            "Run: pip install py-solc-x\n"
            "Or compile with Hardhat and place TouristIdentity.json in contracts/"
        )


def deploy() -> None:
    if not PRIVATE_KEY:
        print("ERROR: BLOCKCHAIN_PRIVATE_KEY not set in environment.")
        print("For Hardhat dev node, use one of the default test account private keys.")
        sys.exit(1)

    print(f"Connecting to blockchain at {PROVIDER_URL}...")
    w3 = Web3(Web3.HTTPProvider(PROVIDER_URL))
    w3.middleware_onion.inject(geth_poa_middleware, layer=0)

    if not w3.is_connected():
        print(f"ERROR: Cannot connect to {PROVIDER_URL}")
        sys.exit(1)

    print(f"Connected. Chain ID: {w3.eth.chain_id}, Block: {w3.eth.block_number}")

    account = w3.eth.account.from_key(PRIVATE_KEY)
    deployer = account.address
    balance = w3.eth.get_balance(deployer)
    print(f"Deployer: {deployer}")
    print(f"Balance: {w3.from_wei(balance, 'ether')} ETH")

    abi_str, bytecode = compile_contract()
    abi = json.loads(abi_str)

    contract = w3.eth.contract(abi=abi, bytecode=bytecode)

    # Build and send deployment transaction
    tx = contract.constructor().build_transaction({
        "chainId": w3.eth.chain_id,
        "from": deployer,
        "nonce": w3.eth.get_transaction_count(deployer),
        "gas": 2_000_000,
        "gasPrice": w3.eth.gas_price,
    })

    signed = account.sign_transaction(tx)
    tx_hash = w3.eth.send_raw_transaction(signed.rawTransaction)
    print(f"Deployment tx: {tx_hash.hex()}")

    receipt = w3.eth.wait_for_transaction_receipt(tx_hash, timeout=120)
    contract_address = receipt.contractAddress

    print(f"\n✅ TouristIdentity deployed!")
    print(f"   Contract address: {contract_address}")
    print(f"   Block: {receipt.blockNumber}")
    print(f"   Gas used: {receipt.gasUsed}")
    print(f"\nAdd to .env:")
    print(f"   BLOCKCHAIN_CONTRACT_ADDRESS={contract_address}")

    # Save ABI to contracts/TouristIdentity.json for future use
    output = {
        "abi": abi,
        "address": contract_address,
        "tx_hash": tx_hash.hex(),
        "block_number": receipt.blockNumber,
    }
    output_path = Path(__file__).parent.parent / "contracts" / "TouristIdentity.json"
    with open(output_path, "w") as f:
        json.dump(output, f, indent=2)
    print(f"   ABI + address saved to: {output_path}")


if __name__ == "__main__":
    deploy()
